send_command:
  fields:
    command:
      required: true
      example: "ON"
      selector:
        text:
    protocol:
      required: true
      example: CHACON
      selector:
        text:
    device_address:
      required: false
      example: A1
      selector:
        text:
    device_id:
      required: false
      example: 40
      selector:
        text:
    automatic_add:
      required: true
      default: false
      selector:
        boolean:
