name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  validate:
    uses: ./.github/workflows/validate.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, validate]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/git@10
            @semantic-release/changelog@6
            @semantic-release/exec@6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
